### ISSUE TITLE
Error labeling of datasets

### ISSUE THREAD

**Issue by xiaoye-hhh** [dyhBUPT/BUPTCampus#1]
Nice work! I found some annotation errors, which seem to be caused by the drift of the tracker. How should these errors be corrected?
These are some examples of errors：
![0](https://github.com/dyhBUPT/BUPTCampus/assets/55238145/5acfef51-e4ec-47c0-ae9f-d044068908c0)
![1](https://github.com/dyhBUPT/BUPTCampus/assets/55238145/9cd1080c-faf1-4c8e-9cbd-929c12da6996)
![2](https://github.com/dyhBUPT/BUPTCampus/assets/55238145/b6b06c30-0dff-4ae8-b229-00e56af6d956)
![3](https://github.com/dyhBUPT/BUPTCampus/assets/55238145/69b683de-e4c0-4afd-b770-059ebc16671c)
![4](https://github.com/dyhBUPT/BUPTCampus/assets/55238145/1222076c-77ee-469a-a7ab-77109cd1f520)

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

The errors are common in existing datasets because of imperfect detection / tracking results.
There are some ways I can think of to deal with it:
1. You can treat them as training / testing noise. And you can try to study robust training / inference methods. Because our samples are tracklets, the noise can be alleviated by appropriate temporal modelling design, maybe.
2. You can fix these errors manually by dropping wrong frames. If you do this, the contribution of a clean version of BUPTCampus dataset is strongly encouraged.

If you have some other ideas, welcome to tell me! ^.^
Best wishes~

**Comment by xiaoye-hhh** [comment]
Thanks!
